### ISSUE TITLE
Complete DG Section 3.3

### ISSUE THREAD

**Issue by NeilBaner** [AY2021S1-CS2113T-T12-3/tp#111]
Complete the DG section pertaining to the Command class, and therefore, the logic of the app.

**Comment by franceneee** [comment]
newer functions not in CliCommands diagram

**Comment by NeilBaner** [comment]
Noted in TODO near it.

**Comment by NeilBaner** [comment]
Pushing to v2.1.

**Comment by yAOwzers** [comment]
@NeilBaner Do you need help with the UML diagrams for this?

**Comment by NeilBaner** [comment]
Wouldn't mind tbh...
