### ISSUE TITLE
Re: DG 4.2.1.2 Aspect How to store tasks in `TaskList`

### ISSUE THREAD

**Issue by franceneee** [AY2021S1-CS2113T-T12-3/tp#189]
@------rishi12438-----: "Are you referring to space or time complexity? You could use an array of a fixed size, lets say 10000 and store it by index. Of course, the number of tasks you can create is limited but since its going to be small. You might want to explore this?"

**Comment by NeilBaner** [comment]
I believe this was fixed somewhere as the section seems to have been updated.

**Comment by franceneee** [comment]
Nope @NeilBaner , it still looks like this 
![image](https://user-images.githubusercontent.com/57038559/98456618-e2f0d600-21ba-11eb-8277-c06239de8060.png)

**Comment by NeilBaner** [comment]
Oh is it the formatting that was the problem? I thought it was the content.

**Comment by franceneee** [comment]
Yes it was the content, but the content also has not changed.
