### ISSUE TITLE
Add JUnit Testing for Storage Class 

### ISSUE THREAD

**Issue by yAOwzers** [AY2021S1-CS2113T-T12-3/tp#86]

**Comment by NeilBaner** [comment]
Is Storage something we should be testing with JUnit? I guess we could test the serialization and deserialization (especially with edge cases).

**Comment by NeilBaner** [comment]
Pushing this to v2.1 (the bugfix release) so we can have more time to discuss the appropriate approach.

**Comment by NeilBaner** [comment]
Determined that JUnit tests are not needed for this component.
